# Generated by Django 2.1.3 on 2018-11-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='Choise_text',
            new_name='Choice_text',
        ),
    ]
